# This workflow will run tests on push to main and new version tags

name: Tests

on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm test
        env:
          ACCOUNT_SUB: ${{secrets.ACCOUNT_SUB}}
          ACCESS_KEY: ${{secrets.ACCESS_KEY}}
          SECRET_KEY: ${{secrets.SECRET_KEY}}
